name: Validate JSON Files

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm install -g ajv-cli@5.0.0

      - name: Download Schema
        run: |
          curl -o schema.json https://raw.githubusercontent.com/Kaqemeex/loot-filters-ui/refs/heads/main/schema.json

      - name: Validate JSON files
        run: |
          find . -type f -name "*.json" -not -path "./schema.json" -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file..."
            if ! ajv validate -s schema.json -d "$file" --all-errors; then
              echo "❌ Validation failed for $file"
              exit 1
            fi
          done 